### ISSUE TITLE
New style tests fail on visit()

### ISSUE THREAD

**Issue by mydea** [emberjs/ember-test-helpers#325] opened 2018-02-15 10:12 UTC
I have just upgraded my app to Ember 3, and wanted to try out the new style tests.
So I generated a new, super basic test (`ember g acceptance-test new-style`), and tried to run it:

```js
import { module, test } from 'qunit';
import { visit, currentURL } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';

module('Acceptance | new style', function(hooks) {
  setupApplicationTest(hooks);

  test('visiting /login', async function(assert) {
    await visit('/login');

    assert.equal(currentURL(), '/login');
  });
});
```

However, I get the following error:

```js
TypeError: Cannot read property 'apply' of undefined
    at setup-application-context.js:27
    at tryCatcher (rsvp.js:215)
    at invokeCallback (rsvp.js:393)
    at publish (rsvp.js:379)
    at rsvp.js:10
    at invoke (backburner.js:205)
    at Queue.flush (backburner.js:125)
    at DeferredActionQueues.flush (backburner.js:278)
    at Backburner.end (backburner.js:410)
    at Backburner._boundAutorunEnd (backburner.js:372)
```

After some debugging, the problem seems to be that in the setup-application-context.js, in this line: 

https://github.com/emberjs/ember-test-helpers/blob/3f34686c527b691cf787037bc7dabb24b2fbdde2/addon-test-support/%40ember/test-helpers/setup-application-context.js#L19

`owner` doesn't seem to have a `visit` method. When I look at the `owner` object in the debugger, I see that it only has `__container__` and `__registry__` properties.

I have updated to all the latest versions of everything, as far as I see:

* ember-cli-qunit: 4.3.1
* ember-qunit: 3.3.1
* @ ember/test-helpers: 0.7.17
* ember-cli: 3.0.0
* ember-source: 3.0.0
* ember-data: 3.0.1

**Comment by Turbo87** [comment] 2018-02-15 10:18
@mydea can you share instructions on how to reproduce this issue in a fresh `ember new` app?

**Comment by rwjblue** [comment] 2018-02-15 12:10
I’m fairly certain that your application is not use `setApplication` in its tests/test-helper.js file. This forces us to make a “fake” owner which only has the registry / container interface. 

We need to add helpful assertions in setup application context when their isn’t an application set...

**Comment by mydea** [comment] 2018-02-16 07:58
Yes, that seemed to be the issue. I was unaware that other changes are needed - I also tried the codemod (https://github.com/rwjblue/ember-qunit-codemod) and everything broke. Also, I was unaware that it is not (easily?) possible to mix and match old/new style tests. It would probably be a good idea to document that, as well as the overall upgrade path - as from blog posts and other pieces of information, I did not grasp everything that was necessary. (This also includes the autoboot = false part, that bit me repeatedly when updating).

**Comment by Turbo87** [comment] 2018-02-16 09:14
> that it is not (easily?) possible to mix and match old/new style tests

actually that should be possible, but you would still have to use `setApplication()` in that case to enable you to use the new helpers

**Comment by josh803316** [comment] 2018-03-01 18:30
How would we adapt this for ember-mocha? I'm running into the same issue after upgrading to Ember3, do I have to find somewhere to use `setApplication`?

```javascript
export function setupAcceptanceTest() {
  emberMochaSetupAcceptanceTest('', {
    Application: TestApplication,

    config: config.APP
  });
...
}
```

**Comment by Turbo87** [comment] 2018-03-01 19:39
you can't use this with `ember-mocha` yet, but we're working on solving this already. you can test out the `master` branch on the `ember-mocha` project if you feel adventurous 😉

**Comment by josh803316** [comment] 2018-03-01 19:57
I'll definitely checkout out master, as I'm adventurous :) 👍   Any idea of a timeline or it's wide open?

**Comment by Turbo87** [comment] 2018-03-01 20:08
If I remember correctly the major remaining thing would be documentation. Other than that it seems to work quite fine already.

**Comment by josh803316** [comment] 2018-03-01 20:16
Awesome, and then ember-cli-mocha referencing the new stuff :) Going to test the new stuff now, thanks so much for the heads up

**Comment by josh803316** [comment] 2018-03-01 20:59
@Turbo87 How would the docs change / what would it look like to setup the application test. I converted the following acceptance test to application, but it's failing with server not defined. Just wondering what the helpers/setup would look like and then how the test would reference them...you guys probably have test examples, I'll check there...

```javascript
describe('Application @ foo_feature.test', function(hooks) {
  setupApplicationTest(hooks);
  beforeEach(function() {
    defaultScenario(server); // 
  });
```

**Comment by Turbo87** [comment] 2018-03-01 21:01
> but it's failing with server not defined

that's probably `ember-cli-mirage` failing to initialize. I'd suggest to try this stuff out without any additional testing addons for now.

**Comment by josh803316** [comment] 2018-03-01 21:04
Ack, yes that is true we are using with `ember-cli-mirage`. Will give it a whirl without first.

**Comment by josh803316** [comment] 2018-03-02 00:12
Just FYI for anyone following, there was a discussion in the ember-slack channel today about this very subject:
https://embercommunity.slack.com/messages/C045C9ABM/

**Comment by gibso** [comment] 2018-03-26 16:17
Are there any news on that issue? Would be great :-)

**Comment by Turbo87** [comment] 2018-03-26 16:23
@gibso which issue specifically? apparently "this issue" includes at least three different things at this point 🙈

**Comment by gibso** [comment] 2018-03-26 16:33
@Turbo87 my fault, i'm asking myself howto access the global server object of Mirage in an acceptance test of ember 3.0.

**Comment by Turbo87** [comment] 2018-03-26 16:47
- update to the latest `ember-cli-mirage` release
- run `setupMirage(hooks)` after `setupApplicationTest(hooks)`
- use `this.server` in your tests

**Comment by Turbo87** [comment] 2018-03-26 16:50
summary of this issue:

1) `setApplication()` stuff is not documented, fixed by https://github.com/emberjs/ember-qunit/pull/320

2) docs for `ember-mocha` are missing, fixed by https://github.com/emberjs/ember-mocha/pull/200

3) support for new testing APIs in `ember-cli-mirage`, fixed by https://github.com/samselikoff/ember-cli-mirage/pull/1263

I'm closing this issue now since all of the mentioned issues have been addressed.

**Closed by Turbo87** 2018-03-26 16:50 UTC

**Comment by gibso** [comment] 2018-03-26 18:20
awesome! thank you!
