### ISSUE TITLE
Integration component test issues after v0.5.31

### ISSUE THREAD

**Issue by calderas** [emberjs/ember-test-helpers#176] opened 2016-08-31 18:37 UTC
After the v0.5.31 release, I started getting an error when running tests. The **first**  (alphabetically) integration component test will always fail to render. Event if it's a very simple test that just renders a div it will fail, so it's consistent (in my app).

When using ember exam with multiple partitions I get the same error for different partitions.
But always just the first integration component test (or first ones when using partitions).

Tracked it down to this line: 
https://github.com/switchfly/ember-test-helpers/compare/v0.5.30...v0.5.31#diff-6131c3a14dd0889855bcf084535928fbR250

This is what renders to the dom instead of the component's content

```
{ type: 'log', text: '\'<!---->\'\n' }
```

It works fine again when I replace this line:

```
 context._element = element = document.querySelector('#ember-testing > .ember-view');
```

with: 

```
context._element = element = Ember.$('#ember-testing > .ember-view');
```

PhantomJS: 2.1.1
Ember: 2.4.5
ember-cli: 2.7.0
ember-cli-qunit: 2.1.0

**Comment by jasonmit** [comment] 2016-09-15 00:08
I'm also seeing this, reverting back to 0.5.31 resolved this.

**Comment by rwjblue** [comment] 2016-09-15 00:58
From my eyes the only difference between those two selectors is that the jQuery one will select all elements that match and the `document.querySelector` one will only match the first...

Can someone create a demo repo showing the issue?

**Comment by jasonmit** [comment] 2016-09-15 00:59
I'll throw one together tonight

**Comment by rwjblue** [comment] 2016-09-15 01:05
Thank you!

**Comment by jasonmit** [comment] 2016-09-15 07:07
@rwjblue I'm now unable to reproduce it, I'll keep an eye out and will report back if I can reproduce+isolate it..

**Comment by rwjblue** [comment] 2016-09-15 11:25
Kk. I was wondering perhaps if it was relate to Ember version and/or whether or not the component under test was tagless.

**Comment by jasonmit** [comment] 2016-09-15 20:42
@rwjblue this happened while upgrading from ~2.6 to 2.8.  We are also on ember-mocha so unsure if that had anything to do with it.

The tests that were failing with this were not tagless components, though we had test failures because of that new assertion but I consider that unrelated to this issue.

**Comment by calderas** [comment] 2016-09-27 20:46
After looking at this again, I found the issue on my app.
There was a DOM element leaking from Acceptance Tests that wasn't removed properly.

Since the new selector only returns the first ".ember-view" it didn't match the one it expected, hence the error on the new version.

Also, the reason this was only breaking the first test is that the HTML gets cleaned up after the component test is done.
https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/abstract-test-module.js#L138
```js
teardownTestElements() {
  document.getElementById('ember-testing').innerHTML = '';
  ...
}
```

I fixed the issue by making sure the element leaking was removed properly on ATs.

Thanks for the input

**Comment by jasonmit** [comment] 2016-09-27 21:34
@calderas that might explain why I wasn't able to reproduce it an example app.  Thanks for reporting back, I'll be sure to look for any components that are leaking elements.

**Comment by Turbo87** [comment] 2016-12-21 14:44
@jasonmit @calderas can we close this? or is this still an issue?

**Comment by calderas** [comment] 2016-12-21 14:56
No longer an issue, thanks!

**Closed** 2016-12-21 14:57 UTC
