### ISSUE TITLE
setupOnError not working

### ISSUE THREAD

**Issue by amk221** [emberjs/ember-test-helpers#1128] opened 2021-09-15 08:50 UTC
[Here](https://github.com/amk221/-ember-setup-on-error/commit/24bb42d2ba3d68bd0381cd639385e43a4bf1102d) are two test cases.

One where a component errors in constructor, and another where it errors in response to a click.

The first can be caught by `setupOnError`, and ignored in the test suite. 👍🏻
The second is not caught by `setupOnError`, and so the test fails. 👎🏻

**Comment by jfdnc** [comment] 2021-10-02 05:08
Interestingly, this causes your failing test here to respect `setupOnerror` and pass:

```javascript
<button type="button" {{on "click" (action this.check)}}>
  check
</button>
```

_with the example invocation binding via `@action` window object onerror called_
![Screen Recording 2021-10-01 at 11 05 54 PM](https://user-images.githubusercontent.com/15672873/135704333-2317347b-f8c7-45b8-b233-42a1eeb3340e.gif)

_using `(action` helper invokes error in the correct context_
![Screen Recording 2021-10-01 at 11 06 27 PM](https://user-images.githubusercontent.com/15672873/135704343-04fbe050-bef0-4b86-bad7-848060dd5de7.gif)

**Comment by jfdnc** [comment] 2021-10-02 23:06
@amk221 Looks like this is a known issue, there is some discussion in the latter part of [this thread](https://github.com/emberjs/ember-qunit/issues/592), which it looks like you were part of but there has been more discussion since your last comment there. Seems to be currently unresolved.

**Comment by buschtoens** [comment] 2022-02-24 10:02
I got fed up with this long-standing issue, so I decided to invest a bit of time and do some detective work. 🕵️😄

This occurs, when an error is thrown outside of the Ember run loop. `setupOnerror` works by hooking into `Ember.onerror`, which in turn [is called by Backburner](https://github.com/emberjs/ember.js/blob/v4.4.0-alpha.3/packages/%40ember/runloop/index.ts#L87-L94) (Ember's backing run loop implementation) when a task in the run loop throws.

The error then propagates to the global [`window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror) handler or [`window.onunhandledrejection`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection), if it's async.

It still shows up as a global failure in your QUnit test, because QUnit catches these via [QUnit.onUncaughtException](https://api.qunitjs.com/extension/QUnit.onUncaughtException/), like @snewcomer correctly pointed out in the issue that you linked: https://github.com/emberjs/ember-qunit/issues/592#issuecomment-971106445

Running outside of a run loop can easily happen by accident, for instance when you manually add an event listener to an element and don't wrap the listener in [`run()`](https://api.emberjs.com/ember/release/classes/@ember%2Frunloop/methods/run?anchor=run).

```ts
import { run } from '@ember/runloop';

element.addEventListener('click', () => {
  run(() => {
    throw Error('caught by `setupOnerror`');
  });
});

element.addEventListener('click', () => {
  throw Error('NOT caught by `setupOnerror`');
})
```

And in fact, if you change your `check` action to throw the error inside a run loop, the test passes!

```ts
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { run } from '@ember/runloop';

export default class MyComponent extends Component {
  @action
  check() {
    run(() => {
      throw new Error('check failed');
    });
  }
}
```

Now the [Ember Guides](https://guides.emberjs.com/release/applications/run-loop/) claim that

> For basic Ember app development scenarios, you don't need to understand the run loop or use it directly. All common paths are paved nicely for you and don't require working with the run loop.

This would lead me to believe that using `{{on "click" this.check}}` and the `click` test helper should _just work™_ out of the box. So why doesn't it?

Ember transparently uses Glimmer's `{{on}}` modifier. Glimmer itself is not integrated with Backburner nor the Ember runloop. It [registers the passed in listener as-is](https://github.com/glimmerjs/glimmer-vm/blob/v0.84.0/packages/@glimmer/runtime/lib/modifiers/on.ts#L198-L224) without wrapping it in `run()` first.

I would consider this is a bug, because it violates the promise made in the Ember Guides that you don't need to concern yourself with `run` when using Ember's standard tools. It doesn't _really_ matter for real-world apps, because [Ember will helpfully wrap calls](https://guides.emberjs.com/release/applications/run-loop/#toc_what-happens-if-i-forget-to-start-a-run-loop-in-an-async-handler) that schedule tasks into a run loop queue into an implicit _autorun_ loop, if they are not called from inside a run loop. The only negative effect of this is slightly worse performance.

This only really becomes an issue in tests, because `Ember.onerror` is not set up to handle errors thrown outside of a run loop, like explained above.

But the trouble doesn't stop there. Regular "native" DOM events initiated by a user action / the browser are handled asynchronously as opposed to synthetic events, i.e. events triggered manually via [`dispatchEvent`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent):

> Unlike "native" events, which are fired by the browser and invoke event handlers asynchronously via the event loop, `dispatchEvent()` invokes event handlers synchronously. All applicable event handlers are called and return before `dispatchEvent()` returns.

`click` and any other DOM test helpers firing events use [`dispatchEvent` via `fireEvent`](https://github.com/emberjs/ember-test-helpers/blob/v2.6.0/addon-test-support/%40ember/test-helpers/dom/fire-event.ts#L131). And since `dispatchEvent` triggers the event listeners _synchronously_, one would hope that, even if `setupOnerror` doesn't work, the error would at least propagate through to `click`:

```ts
try {
  await click('.some-element-that-throws-on-click');
} catch (error) {
  console.log(error); // This should log the error from the click handler.
}
```

Alas, that also doesn't work: #310, #453, #440

But why? Even though `dispatchEvent` calls all listeners synchronously, it doesn't propagate any of the errors they might throw. So there again, the only option is to handle them in a global error handler. As of now, that's `window.onerror`, which QUnit hooks into and then fails the test with the out of band global failure, like explained above.

Ideally though, the handler would be wrapped in a run loop, so that `Ember.onerror` can catch it instead. That would allow for handling it via `setupOnerror`, but the `click` helper _still_ wouldn't throw, because it doesn't hook into `Ember.onerror` to watch for errors thrown during the execution of the event listeners.

**Comment by amk221** [comment] 2024-01-31 12:05
What's the situation with this? It's happening more and more.

eslint-plugin-ember recently added a `no-runloop` [rule](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-runloop.md).

We were using `run(() => {}` to temporarily fix this.

**Comment by NullVoxPopuli** [comment] 2024-01-31 15:03
Don't use runloop to 'get around' this.

You can use try/catch for exceptions from click events, or assert.throws.

:) <3

setupOnerror is only for runloop stuff, which is why putting stuff in runloop queues makes errors show up there

**Comment by amk221** [comment] 2024-01-31 15:10
How  are we supposed to test error scenarios in acceptance tests though? They cause the tests to fail, which is why we use `setupOnError` to squelch it.

**Comment by NullVoxPopuli** [comment] 2024-01-31 15:15
Can you provide a minimal repro of your specific example?

It's totally valid atm to use setupOnerror for rendering errors and assert.throws for others, atd try/catch for others - which should cover your bases)

**Comment by amk221** [comment] 2024-01-31 15:56
https://github.com/amk221/-ember-unhappy-path-test/commit/2797b67a644d14014feb4167aa0a1b0a91d679b0

**Comment by NullVoxPopuli** [comment] 2024-01-31 18:22
there are no failing tests on the `main` branch :-\

**Comment by amk221** [comment] 2024-01-31 18:29
It’s [commented](https://github.com/amk221/-ember-unhappy-path-test/commit/2797b67a644d14014feb4167aa0a1b0a91d679b0#diff-5fdf940d3833a427d5a68966cee01fe9e6fc093e5a0a19c0f4086a5023972f08R11) as to why

**Comment by NullVoxPopuli** [comment] 2024-01-31 23:52
gotchya, well, discovered some things,

It seems this is related to a limitation in _The Platform_ for certain styles of throwing errors.

I made a demo here to demonstrate (and to remove all possible ember/qunit suspicions)
 
https://jsbin.com/jakecim/edit?html,output

In particular, when _catching_ errors (event listening, etc), "uncaught (in promise)" errors _always_ reach the "root" / console / browser, and it doesn't seem there is a way to "stopPropagation", as you would with click event handlers.


This seems to back up the experience of others as well:
- https://stackoverflow.com/questions/62100577/event-preventdefault-does-not-seem-to-work-async-context
  > After a few experiments I seem to find that the only way I can find to prevent this is to swallow the error (using try...catch) at some point, preferably at the highest async call in the stack (or rather in the sequence of calls of async functions), if that can be determined.
  
  
So, in the JSBin demo, I've added a checkbox (enabled by default) which makes the click-handler async/await (so that the click handler does not lose track of the async stack), and then _all 3 scenarios_ (async, promise chain, and sync), are correctly caught and don't bubble up to the window -- unchecking this checkboxe reproduces the behavior you're experiencing in your app -- I believe this solution is in alignment with what others have discovered as well (the stackoverflow, for example).


  
I'm going to close this issue, as I don't think there is anything better we can do with `setupOnerror`.

If someone can come up with some way "preventDefault" / "stopPropagation" on error-event handlers, at some point in the future, let's open up a new issue and discuss there -- as I do agree with ya'll that it'd be great to have some unified way to test/assert/capture errors in tests.

**Closed by NullVoxPopuli** 2024-01-31 23:52 UTC

**Comment by amk221** [comment] 2024-02-01 09:41
Where does that leave us though? It's impossible to test certain things, consider:

```js
export default class extends Component {
  constructor() {
    super(...arguments);

    assert('@foo must be provided', 'foo' in this.args);
  }
}
```

```js
test('foo', async function(assert) {
  assert.expect(1);

  setupOnerror((error) => {
    if (
      error.message === 'Assertion Failed: @foo must be provided'
    ) {
      assert.step('ensures correct usage');
      return;
    }

    throw error;
  });

  await render(hbs`<MyComponent />`);

  assert.verifySteps(['ensures correct usage']);
});
```

**Comment by mansona** [comment] 2024-02-01 10:36
@amk221 I wonder about a test like that though 🤔 the implementation of `assert` is that it it won't run in a production build so that it's less strict and would throw fewer errors for end-users. assert itself is a helpful tool for developers to identify problems during development and not something that we should be testing.

I understand that this could just be used for an illustration but the reason I am asking is because it could be that you should be testing at a different layer rather than trying to "catch" exceptions thrown in constructors of components 🤔

**Comment by amk221** [comment] 2024-02-01 10:41
Yeh, I know they are stripped, it's to help guide developers. But yes, for example purposes only. There are still scenarios that are [untestable](https://github.com/emberjs/ember-qunit/issues/592).

**Comment by NullVoxPopuli** [comment] 2024-02-01 14:39
> It's impossible to test certain things
> There are still scenarios that are https://github.com/emberjs/ember-qunit/issues/592#issuecomment-1920804323.

This isn't true -- https://github.com/emberjs/ember-test-helpers/issues/1128#issuecomment-1920196763 provided ways to capture all sorts of errors, exceptions, from anywhere.

Now, if you mean _with `setupOnerror`, then sure. Let's explore improving `setupOnerror` for users of chrome-based browsers :tada:

**Comment by amk221** [comment] 2024-02-01 22:21
> This isn't true

I don't understand why the issue is closed with "solution is probably this" 🤔.  I must be missing something glaringly obvious.... Because nothing I've seen can get the acceptance tests in github.com/amk221/-ember-unhappy-path-test/commit/2797b67a644d14014feb4167aa0a1b0a91d679b0 to pass once the error reaches the window.

I'm happy to wash my hands of `setupOnerror`, if there was a solution that isn't a "probably" solution, but an actual one.

**Comment by NullVoxPopuli** [comment] 2024-02-01 23:20
Made an example: https://github.com/amk221/-ember-unhappy-path-test/pull/1

![image](https://github.com/emberjs/ember-test-helpers/assets/199018/a51484eb-0c81-4c82-9f0e-f5b589d4102a)


There is another example of how to do this here: https://github.com/qunitjs/qunit/issues/1419#issuecomment-561739486 -- albeit, not contextually ergonomic.

So, I've opened this issue on the QUnit repo, where I think we should figure out some solution for QUnit v3. https://github.com/qunitjs/qunit/issues/1736

Maybe _it's qunit_ that needs to provide setupOnError / resetOnError (or similar) for handling this situation.
